# Delete these routes and define your own shop routes here

acme_sylius_tpay_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Acme\SyliusTpayPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

acme_sylius_tpay_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Acme\SyliusTpayPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
